import os
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from pptx import Presentation
from pptx.util import Inches
from docx import Document
from io import BytesIO
from fastapi.responses import StreamingResponse

router = APIRouter()

class ExportRequest(BaseModel):
    document_id: str
    analysis_data: dict # Expects a dict with keys: company, market, financial, risk

@router.post("/export/pptx")
async def export_pptx(request: ExportRequest):
    try:
        prs = Presentation()
        
        # Title Slide
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = f"Investment Analysis: {request.document_id}"
        subtitle.text = "Generated by AI Pitchbook Evaluator"

        # Helper to add content slides
        def add_slide(header, content):
            layout = prs.slide_layouts[1] # Title and Content
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = header
            slide.placeholders[1].text = content

        # Add Analysis Slides
        if "company" in request.analysis_data:
            add_slide("Company Overview", request.analysis_data["company"])
        if "market" in request.analysis_data:
            add_slide("Market Analysis", request.analysis_data["market"])
        if "financial" in request.analysis_data:
            add_slide("Financial Analysis", request.analysis_data["financial"])
        if "risk" in request.analysis_data:
            add_slide("Risk Assessment", request.analysis_data["risk"])

        # Save to stream
        output = BytesIO()
        prs.save(output)
        output.seek(0)
        
        headers = {
            'Content-Disposition': f'attachment; filename="analysis_{request.document_id}.pptx"'
        }
        return StreamingResponse(output, headers=headers, media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/export/docx")
async def export_docx(request: ExportRequest):
    try:
        doc = Document()
        doc.add_heading(f'Investment Committee Paper: {request.document_id}', 0)

        # Helper to add sections
        def add_section(header, content):
            doc.add_heading(header, level=1)
            doc.add_paragraph(content)

        # Add Sections
        if "company" in request.analysis_data:
            add_section("1. Company Overview", request.analysis_data["company"])
        if "market" in request.analysis_data:
            add_section("2. Market Analysis", request.analysis_data["market"])
        if "financial" in request.analysis_data:
            add_section("3. Financial Analysis", request.analysis_data["financial"])
        if "risk" in request.analysis_data:
            add_section("4. Risk Assessment", request.analysis_data["risk"])

        # Save to stream
        output = BytesIO()
        doc.save(output)
        output.seek(0)
        
        headers = {
            'Content-Disposition': f'attachment; filename="investment_paper_{request.document_id}.docx"'
        }
        return StreamingResponse(output, headers=headers, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
